root: true
env:
  es2022: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:n/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files:
      - '**/*.test.ts'
    env:
      node: true
      es2022: true
      vitest: true
    extends:
      - eslint:recommended
      - plugin:import/recommended
      - plugin:n/recommended
      - prettier
    rules: {}
