parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project:
    - '**/tsconfig.json'
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:n/recommended
  - 'plugin:@typescript-eslint/recommended'
  - prettier
plugins:
  - '@typescript-eslint'
  - eslint-plugin-import
  - eslint-plugin-n
  - prettier
