parserOptions:
  ecmaVersion: latest
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:n/recommended
  - prettier
plugins:
  - eslint-plugin-import
  - eslint-plugin-n
  - prettier
