name: Changesets — Version PR (reusable)

# Explicit token permissions for Changesets to open/update the Version Packages PR
permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:

concurrency:
  group: changesets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  open_or_update_version_pr:
    name: Open/Update "Version Packages" PR
    # Do not fail the caller if this flakes; a later run can retry
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Use the official Changesets Action to drive a PR-based versioning flow.
      # It will open (or update) a branch like "changeset-release/main" and a PR titled "Version Packages"
      # that contains the version bumps and changelog updates. It does NOT push to main directly.
      - name: Changesets — create or update PR
        uses: changesets/action@v1
        with:
          # Run the standard version command inside the PR branch
          version: pnpm changeset version
          title: Version Packages
          commit: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
